#!/usr/bin/env bash
#

xrandr --output "LVDS-1" --mode "1366x768" 
xrandr --output "VGA-1"  --mode "1920x1080"
xrandr --output "HDMI-1" --mode "1920x1080"
xrandr --auto --output "LVDS-1" --rotate normal --primary --output "VGA-1" --rotate normal --right-of "LVDS-1" --output "HDMI-1" --rotate left --left-of "LVDS-1"

xrandr --newmode "1920x1080_60.00"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
xrandr --newmode "1368x768_60.00"   85.25  1368 1440 1576 1784  768 771 781 798 -hsync +vsync

xrandr --addmode "HDMI-1" "1920x1080_60.00"
xrandr --addmode "VGA-1"  "1920x1080_60.00"
xrandr --addmode "LVDS-1" "1368x768_60.00" 
