Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'posva/vim-vue'
Plug 'ryanoasis/vim-devicons'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-abolish'
Plug 'machakann/vim-highlightedyank'
Plug 'vim-scripts/AutoComplPop'
Plug 'vim-scripts/Tabular'
Plug 'diepm/vim-rest-console'
Plug '~/.fzf'
" Plug 'zivyangll/git-blame.vim'
